// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrReLfxDJq00VE7EsXfb6EacsxBA-nI1g',
    appId: '1:541179908925:web:6eed586e82d2605a302b54',
    messagingSenderId: '541179908925',
    projectId: 'ecopulsedb1',
    authDomain: 'ecopulsedb1.firebaseapp.com',
    storageBucket: 'ecopulsedb1.firebasestorage.app',
    measurementId: 'G-DH6ZM4CJEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQmxaznUqYhY2pBXGPPSnUNZUeFyjjqo',
    appId: '1:541179908925:android:8eebb092cd4cfb9b302b54',
    messagingSenderId: '541179908925',
    projectId: 'ecopulsedb1',
    storageBucket: 'ecopulsedb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQ2srqxS-Tj_4x1yyoAIeAIeAzene5SM',
    appId: '1:541179908925:ios:741c3fb5163c13ad302b54',
    messagingSenderId: '541179908925',
    projectId: 'ecopulsedb1',
    storageBucket: 'ecopulsedb1.firebasestorage.app',
    iosBundleId: 'com.ecopulse.ecopulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQ2srqxS-Tj_4x1yyoAIeAIeAzene5SM',
    appId: '1:541179908925:ios:741c3fb5163c13ad302b54',
    messagingSenderId: '541179908925',
    projectId: 'ecopulsedb1',
    storageBucket: 'ecopulsedb1.firebasestorage.app',
    iosBundleId: 'com.ecopulse.ecopulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrReLfxDJq00VE7EsXfb6EacsxBA-nI1g',
    appId: '1:541179908925:web:a7845d477ffcc61e302b54',
    messagingSenderId: '541179908925',
    projectId: 'ecopulsedb1',
    authDomain: 'ecopulsedb1.firebaseapp.com',
    storageBucket: 'ecopulsedb1.firebasestorage.app',
    measurementId: 'G-DXVTRKYWRZ',
  );
}
